### ISSUE TITLE
Windows 1252 encoding in Include/stm32u0xx.h

### ISSUE THREAD

**Issue by blackbird998** [STMicroelectronics/cmsis-device-u0#2]
Hi,
In file `@brief` the ( ’ ) character in `peripheral’s` (lines 11 and 12) is Windows 1252 encoded instead of UTF-8.
```markdown
  *              - To use or not the peripheral’s drivers in application code(i.e.
  *                code will be based on direct access to peripheral’s registers
  *                rather than drivers API), this option is controlled by
  *                "#define USE_HAL_DRIVER"
 ```

Kind regards,
Adam

**Comment by KRASTM** [comment]
Hello @blackbird998,

Thank you for the report.

We confirm the point, and it will be fixed.

With regards,

**Comment by KRASTM** [comment]
Fixed in commit: https://github.com/STMicroelectronics/cmsis-device-u0/commit/1d5ad465f74a534033c4cbb4aee084c2b6bba3d7
